### ISSUE TITLE
Support for Power Monitoring?

### ISSUE THREAD

**Issue by buzzy** [jdpiercy/Kankun-SmartPlug#1]
This is not really an issue, but I thought this would be the best place to ask this question.

I bought my device several years ago, but thought I would put some time to it now.
I remember there was a Google+ group with lots of good information, but as Google+ is terminated, all that info is now lost.

When I bought my device, it was marketed as supporting "Power Monitoring". Printed on the packaging and everything. I also recall someone explaining how to read the current value from somewhere in "/sys".

Did you ever find out how to do this? I haven't opened my device yet to check if there is a "current/voltage" chip inside, so I don't know if these devices actually support it.

But if you check on this link:
https://m.qoo10.sg/gmkt.inc/Goods/GoodsDetailOriginal.aspx?__ar=Y&goodscode=417754180&from=gdetail

You can see that it is advertised with a feature that "cuts the power when phone finishes charging". The only way it can do that, is to monitor the power usage and cut power if it sees that there is no (or very low) current usage. That suggests that there is some kind of chip that reports this to the system.

**Comment by jdpiercy** [comment]
Sorry for the super late response. I haven't worked on these smart plugs forever, but plan to build out a new and prob final firmware for them as I still have approx. 20 of these units in service. I do remember seeing that feature in the manual, I will explore both the original firmware and the PCB of the device.

However I think that this feature was implemented in the original application and you needed the app on the phone and it just triggered the plug off once it saw the phone was charged up.
